#!/bin/sh
set -eu

POETRY_DB="${POETRY_POSTGRES_DB:-poetry}"
POETRY_USER="${POETRY_POSTGRES_USER:-poetry_user}"
POETRY_PASSWORD="${POETRY_POSTGRES_PASSWORD:-change-me-poetry-db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POETRY_USER}') THEN
    CREATE ROLE ${POETRY_USER} LOGIN PASSWORD '${POETRY_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${POETRY_DB} OWNER ${POETRY_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POETRY_DB}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${POETRY_DB} TO ${POETRY_USER};
EOSQL

