#!/bin/sh
set -eu

NEWS_DB="${NEWS_POSTGRES_DB:-news}"
NEWS_USER="${NEWS_POSTGRES_USER:-news_user}"
NEWS_PASSWORD="${NEWS_POSTGRES_PASSWORD:-change-me-news-db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${NEWS_USER}') THEN
    CREATE ROLE ${NEWS_USER} LOGIN PASSWORD '${NEWS_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${NEWS_DB} OWNER ${NEWS_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${NEWS_DB}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${NEWS_DB} TO ${NEWS_USER};
EOSQL

