#!/bin/sh
set -eu

BUDGET_DB="${BUDGET_POSTGRES_DB:-budget}"
BUDGET_USER="${BUDGET_POSTGRES_USER:-budget_user}"
BUDGET_PASSWORD="${BUDGET_POSTGRES_PASSWORD:-change-me-budget-db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${BUDGET_USER}') THEN
    CREATE ROLE ${BUDGET_USER} LOGIN PASSWORD '${BUDGET_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${BUDGET_DB} OWNER ${BUDGET_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${BUDGET_DB}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${BUDGET_DB} TO ${BUDGET_USER};
EOSQL
