#!/bin/sh
set -eu

REMINDERS_DB="${REMINDERS_POSTGRES_DB:-reminders}"
REMINDERS_USER="${REMINDERS_POSTGRES_USER:-reminders_user}"
REMINDERS_PASSWORD="${REMINDERS_POSTGRES_PASSWORD:-change-me-reminders-db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${REMINDERS_USER}') THEN
    CREATE ROLE ${REMINDERS_USER} LOGIN PASSWORD '${REMINDERS_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${REMINDERS_DB} OWNER ${REMINDERS_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${REMINDERS_DB}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${REMINDERS_DB} TO ${REMINDERS_USER};
EOSQL
