#!/bin/sh
set -eu

PORTUGUESE_EXPENSES_DB="${PORTUGUESE_EXPENSES_POSTGRES_DB:-portuguese_expenses}"
PORTUGUESE_EXPENSES_USER="${PORTUGUESE_EXPENSES_POSTGRES_USER:-portuguese_expenses_user}"
PORTUGUESE_EXPENSES_PASSWORD="${PORTUGUESE_EXPENSES_POSTGRES_PASSWORD:-change-me-portuguese-expenses-db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${PORTUGUESE_EXPENSES_USER}') THEN
    CREATE ROLE ${PORTUGUESE_EXPENSES_USER} LOGIN PASSWORD '${PORTUGUESE_EXPENSES_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${PORTUGUESE_EXPENSES_DB} OWNER ${PORTUGUESE_EXPENSES_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PORTUGUESE_EXPENSES_DB}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${PORTUGUESE_EXPENSES_DB} TO ${PORTUGUESE_EXPENSES_USER};
EOSQL
