#!/bin/sh
set -eu

DOC_FORGE_DB="${DOC_FORGE_POSTGRES_DB:-doc_forge}"
DOC_FORGE_USER="${DOC_FORGE_POSTGRES_USER:-doc_forge_user}"
DOC_FORGE_PASSWORD="${DOC_FORGE_POSTGRES_PASSWORD:-change-me-doc-forge-db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DOC_FORGE_USER}') THEN
    CREATE ROLE ${DOC_FORGE_USER} LOGIN PASSWORD '${DOC_FORGE_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${DOC_FORGE_DB} OWNER ${DOC_FORGE_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DOC_FORGE_DB}')\gexec

GRANT ALL PRIVILEGES ON DATABASE ${DOC_FORGE_DB} TO ${DOC_FORGE_USER};
EOSQL
